/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      colors: {
        /* ── Backgrounds ─────────────────────────────────────── */
        background: {
          DEFAULT: 'var(--rare-bg)',
          alt: 'var(--rare-bg-alt)',
          hover: 'var(--rare-bg-hover)',
          solid: 'var(--rare-bg-solid)',
          secondary: 'var(--rare-bg-secondary)',
          'secondary-alt': 'var(--rare-bg-secondary-alt)',
          'secondary-hover': 'var(--rare-bg-secondary-hover)',
          'secondary-subtle': 'var(--rare-bg-secondary-subtle)',
          'secondary-solid': 'var(--rare-bg-secondary-solid)',
          tertiary: 'var(--rare-bg-tertiary)',
          quaternary: 'var(--rare-bg-quaternary)',
          active: 'var(--rare-bg-active)',
          'active-hover': 'var(--rare-bg-active-hover)',
          disabled: 'var(--rare-bg-disabled)',
          'disabled-subtle': 'var(--rare-bg-disabled-subtle)',
          overlay: 'var(--rare-bg-overlay)',
          brand: 'var(--rare-bg-brand)',
          'brand-alt': 'var(--rare-bg-brand-alt)',
          'brand-secondary': 'var(--rare-bg-brand-secondary)',
          'brand-secondary-alt': 'var(--rare-bg-brand-secondary-alt)',
          'brand-solid': 'var(--rare-bg-brand-solid)',
          'brand-solid-hover': 'var(--rare-bg-brand-solid-hover)',
          'brand-section': 'var(--rare-bg-brand-section)',
          'brand-section-subtle': 'var(--rare-bg-brand-section-subtle)',
          error: 'var(--rare-bg-error)',
          'error-secondary': 'var(--rare-bg-error-secondary)',
          'error-solid': 'var(--rare-bg-error-solid)',
          'error-solid-hover': 'var(--rare-bg-error-solid-hover)',
          warning: 'var(--rare-bg-warning)',
          'warning-secondary': 'var(--rare-bg-warning-secondary)',
          'warning-solid': 'var(--rare-bg-warning-solid)',
          'warning-solid-hover': 'var(--rare-bg-warning-solid-hover)',
          success: 'var(--rare-bg-success)',
          'success-secondary': 'var(--rare-bg-success-secondary)',
          'success-solid': 'var(--rare-bg-success-solid)',
          'success-solid-hover': 'var(--rare-bg-success-solid-hover)',
        },
        /* ── Text (typography) ───────────────────────────────── */
        foreground: {
          DEFAULT: 'var(--rare-text)',
          'on-brand': 'var(--rare-text-on-brand)',
          secondary: 'var(--rare-text-secondary)',
          'secondary-on-brand': 'var(--rare-text-secondary-on-brand)',
          tertiary: 'var(--rare-text-tertiary)',
          'tertiary-on-brand': 'var(--rare-text-tertiary-on-brand)',
          muted: 'var(--rare-text-muted)',
          'muted-on-brand': 'var(--rare-text-muted-on-brand)',
          white: 'var(--rare-text-white)',
          disabled: 'var(--rare-text-disabled)',
          'disabled-subtle': 'var(--rare-text-disabled-subtle)',
          placeholder: 'var(--rare-text-placeholder)',
          'placeholder-subtle': 'var(--rare-text-placeholder-subtle)',
          brand: 'var(--rare-text-brand)',
          'brand-dark': 'var(--rare-text-brand-dark)',
          'brand-secondary': 'var(--rare-text-brand-secondary)',
          'brand-tertiary': 'var(--rare-text-brand-tertiary)',
          'brand-tertiary-alt': 'var(--rare-text-brand-tertiary-alt)',
          error: 'var(--rare-text-error)',
          'error-dark': 'var(--rare-text-error-dark)',
          warning: 'var(--rare-text-warning)',
          'warning-dark': 'var(--rare-text-warning-dark)',
          success: 'var(--rare-text-success)',
          'success-dark': 'var(--rare-text-success-dark)',
        },
        /* ── Icon / Decorative FG ────────────────────────────── */
        fg: {
          DEFAULT: 'var(--rare-fg)',
          secondary: 'var(--rare-fg-secondary)',
          tertiary: 'var(--rare-fg-tertiary)',
          muted: 'var(--rare-fg-muted)',
          subtle: 'var(--rare-fg-subtle)',
          faint: 'var(--rare-fg-faint)',
          white: 'var(--rare-fg-white)',
          disabled: 'var(--rare-fg-disabled)',
          'disabled-subtle': 'var(--rare-fg-disabled-subtle)',
          brand: 'var(--rare-fg-brand)',
          'brand-alt': 'var(--rare-fg-brand-alt)',
          'brand-secondary': 'var(--rare-fg-brand-secondary)',
          error: 'var(--rare-fg-error)',
          'error-secondary': 'var(--rare-fg-error-secondary)',
          warning: 'var(--rare-fg-warning)',
          'warning-secondary': 'var(--rare-fg-warning-secondary)',
          success: 'var(--rare-fg-success)',
          'success-secondary': 'var(--rare-fg-success-secondary)',
        },
        /* ── Border ──────────────────────────────────────────── */
        border: {
          DEFAULT: 'var(--rare-border)',
          secondary: 'var(--rare-border-secondary)',
          tertiary: 'var(--rare-border-tertiary)',
          disabled: 'var(--rare-border-disabled)',
          'disabled-subtle': 'var(--rare-border-disabled-subtle)',
          brand: 'var(--rare-border-brand)',
          'brand-solid': 'var(--rare-border-brand-solid)',
          'brand-solid-alt': 'var(--rare-border-brand-solid-alt)',
          error: 'var(--rare-border-error)',
          'error-solid': 'var(--rare-border-error-solid)',
          warning: 'var(--rare-border-warning)',
          'warning-solid': 'var(--rare-border-warning-solid)',
          success: 'var(--rare-border-success)',
          'success-solid': 'var(--rare-border-success-solid)',
        },
        /* ── Primitive Scales ────────────────────────────────── */
        brand: {
          25: 'var(--rare-brand-25)', 50: 'var(--rare-brand-50)',
          100: 'var(--rare-brand-100)', 200: 'var(--rare-brand-200)',
          300: 'var(--rare-brand-300)', 400: 'var(--rare-brand-400)',
          500: 'var(--rare-brand-500)', 600: 'var(--rare-brand-600)',
          700: 'var(--rare-brand-700)', 800: 'var(--rare-brand-800)',
          900: 'var(--rare-brand-900)', 950: 'var(--rare-brand-950)',
        },
        /* ── Button tokens ───────────────────────────────────── */
        'btn-primary': {
          bg: 'var(--rare-btn-primary-bg)',
          border: 'var(--rare-btn-primary-border)',
          fg: 'var(--rare-btn-primary-fg)',
          'bg-hover': 'var(--rare-btn-primary-bg-hover)',
          'border-hover': 'var(--rare-btn-primary-border-hover)',
          'fg-hover': 'var(--rare-btn-primary-fg-hover)',
        },
        'btn-secondary': {
          bg: 'var(--rare-btn-secondary-bg)',
          border: 'var(--rare-btn-secondary-border)',
          fg: 'var(--rare-btn-secondary-fg)',
          'bg-hover': 'var(--rare-btn-secondary-bg-hover)',
          'border-hover': 'var(--rare-btn-secondary-border-hover)',
          'fg-hover': 'var(--rare-btn-secondary-fg-hover)',
        },
        'btn-secondary-color': {
          bg: 'var(--rare-btn-secondary-color-bg)',
          border: 'var(--rare-btn-secondary-color-border)',
          fg: 'var(--rare-btn-secondary-color-fg)',
          'bg-hover': 'var(--rare-btn-secondary-color-bg-hover)',
          'border-hover': 'var(--rare-btn-secondary-color-border-hover)',
          'fg-hover': 'var(--rare-btn-secondary-color-fg-hover)',
        },
        'btn-tertiary': {
          fg: 'var(--rare-btn-tertiary-fg)',
          'bg-hover': 'var(--rare-btn-tertiary-bg-hover)',
          'fg-hover': 'var(--rare-btn-tertiary-fg-hover)',
        },
        'btn-tertiary-color': {
          fg: 'var(--rare-btn-tertiary-color-fg)',
          'bg-hover': 'var(--rare-btn-tertiary-color-bg-hover)',
          'fg-hover': 'var(--rare-btn-tertiary-color-fg-hover)',
        },
        /* ── Node category accents (project-specific) ────────── */
        cat: {
          io: '#3b82f6',
          ai: '#a855f7',
          transform: '#22c55e',
          logic: '#f59e0b',
          integration: '#ef4444',
          utility: '#6b7280',
        },
      },
      /* ── Border color utilities ────────────────────────────── */
      borderColor: {
        DEFAULT: 'var(--rare-border)',
        primary: 'var(--rare-border)',
        secondary: 'var(--rare-border-secondary)',
        tertiary: 'var(--rare-border-tertiary)',
        disabled: 'var(--rare-border-disabled)',
        'disabled-subtle': 'var(--rare-border-disabled-subtle)',
        brand: 'var(--rare-border-brand)',
        'brand-solid': 'var(--rare-border-brand-solid)',
        'brand-solid-alt': 'var(--rare-border-brand-solid-alt)',
        error: 'var(--rare-border-error)',
        'error-solid': 'var(--rare-border-error-solid)',
        warning: 'var(--rare-border-warning)',
        'warning-solid': 'var(--rare-border-warning-solid)',
        success: 'var(--rare-border-success)',
        'success-solid': 'var(--rare-border-success-solid)',
      },
      /* ── Spacing scale ─────────────────────────────────────── */
      spacing: {
        xxs: 'var(--rare-spacing-xxs, 2px)',
        xs: 'var(--rare-spacing-xs, 4px)',
        sm: 'var(--rare-spacing-sm, 6px)',
        md: 'var(--rare-spacing-md, 8px)',
        lg: 'var(--rare-spacing-lg, 10px)',
        xl: 'var(--rare-spacing-xl, 12px)',
        '2xl': 'var(--rare-spacing-2xl, 16px)',
        '3xl': 'var(--rare-spacing-3xl, 20px)',
        '4xl': 'var(--rare-spacing-4xl, 24px)',
        '5xl': 'var(--rare-spacing-5xl, 32px)',
        '6xl': 'var(--rare-spacing-6xl, 36px)',
        '7xl': 'var(--rare-spacing-7xl, 40px)',
        '8xl': 'var(--rare-spacing-8xl, 48px)',
        '9xl': 'var(--rare-spacing-9xl, 52px)',
        '10xl': 'var(--rare-spacing-10xl, 60px)',
        '11xl': 'var(--rare-spacing-11xl, 64px)',
        '12xl': 'var(--rare-spacing-12xl, 80px)',
        '13xl': 'var(--rare-spacing-13xl, 96px)',
        '14xl': 'var(--rare-spacing-14xl, 128px)',
        '15xl': 'var(--rare-spacing-15xl, 160px)',
      },
      /* ── Border radius ─────────────────────────────────────── */
      borderRadius: {
        none: 'var(--rare-radius-none, 0px)',
        xxs: 'var(--rare-radius-xxs, 2px)',
        xs: 'var(--rare-radius-xs, 4px)',
        sm: 'var(--rare-radius-sm, 6px)',
        md: 'var(--rare-radius-md, 8px)',
        lg: 'var(--rare-radius-lg, 10px)',
        xl: 'var(--rare-radius-xl, 12px)',
        '2xl': 'var(--rare-radius-2xl, 16px)',
        '3xl': 'var(--rare-radius-3xl, 20px)',
        '4xl': 'var(--rare-radius-4xl, 24px)',
        full: 'var(--rare-radius-full, 9999px)',
      },
      /* ── Typography ────────────────────────────────────────── */
      fontSize: {
        xxs: ['var(--rare-font-text-xxs, 10px)', { lineHeight: 'var(--rare-line-height-text-xxs, 15px)' }],
        xs: ['var(--rare-font-text-xs, 12px)', { lineHeight: 'var(--rare-line-height-text-xs, 18px)' }],
        sm: ['var(--rare-font-text-sm, 14px)', { lineHeight: 'var(--rare-line-height-text-sm, 20px)' }],
        base: ['var(--rare-font-text-md, 16px)', { lineHeight: 'var(--rare-line-height-text-md, 24px)' }],
        lg: ['var(--rare-font-text-lg, 18px)', { lineHeight: 'var(--rare-line-height-text-lg, 28px)' }],
        xl: ['var(--rare-font-text-xl, 20px)', { lineHeight: 'var(--rare-line-height-text-xl, 30px)' }],
        'display-xs': ['var(--rare-font-display-xs, 24px)', { lineHeight: 'var(--rare-line-height-display-xs, 32px)' }],
        'display-sm': ['var(--rare-font-display-sm, 30px)', { lineHeight: 'var(--rare-line-height-display-sm, 38px)' }],
        'display-md': ['var(--rare-font-display-md, 36px)', { lineHeight: 'var(--rare-line-height-display-md, 44px)', letterSpacing: 'var(--rare-tracking-display-md, -0.72px)' }],
        'display-lg': ['var(--rare-font-display-lg, 48px)', { lineHeight: 'var(--rare-line-height-display-lg, 60px)', letterSpacing: 'var(--rare-tracking-display-lg, -0.96px)' }],
        'display-xl': ['var(--rare-font-display-xl, 60px)', { lineHeight: 'var(--rare-line-height-display-xl, 72px)', letterSpacing: 'var(--rare-tracking-display-xl, -1.2px)' }],
        'display-2xl': ['var(--rare-font-display-2xl, 72px)', { lineHeight: 'var(--rare-line-height-display-2xl, 90px)', letterSpacing: 'var(--rare-tracking-display-2xl, -1.44px)' }],
      },
      /* ── Elevation — Shadow + Focus ────────────────────────── */
      boxShadow: {
        xs: 'var(--rare-shadow-xs)',
        sm: 'var(--rare-shadow-sm)',
        md: 'var(--rare-shadow-md)',
        lg: 'var(--rare-shadow-lg)',
        xl: 'var(--rare-shadow-xl)',
        '2xl': 'var(--rare-shadow-2xl)',
        '3xl': 'var(--rare-shadow-3xl)',
        'focus-ring-brand': 'var(--rare-focus-ring-brand)',
        'focus-ring-gray': 'var(--rare-focus-ring-gray)',
        'focus-ring-gray-secondary': 'var(--rare-focus-ring-gray-secondary)',
        'focus-ring-error': 'var(--rare-focus-ring-error)',
        'focus-ring-brand-xs': 'var(--rare-focus-ring-brand), var(--rare-shadow-xs)',
        'focus-ring-brand-sm': 'var(--rare-focus-ring-brand), var(--rare-shadow-sm)',
        'focus-ring-gray-xs': 'var(--rare-focus-ring-gray), var(--rare-shadow-xs)',
        'focus-ring-gray-sm': 'var(--rare-focus-ring-gray), var(--rare-shadow-sm)',
        'focus-ring-error-xs': 'var(--rare-focus-ring-error), var(--rare-shadow-xs)',
      },
      /* ── Animation timing ──────────────────────────────────── */
      transitionDuration: {
        fast: 'var(--rare-duration-fast, 150ms)',
        normal: 'var(--rare-duration-normal, 300ms)',
        slow: 'var(--rare-duration-slow, 500ms)',
        slower: 'var(--rare-duration-slower, 700ms)',
      },
      transitionTimingFunction: {
        'ease-out-emphasized': 'var(--rare-easing-ease-out, cubic-bezier(0.16, 1, 0.3, 1))',
        'ease-in-out-smooth': 'var(--rare-easing-ease-in-out, cubic-bezier(0.65, 0, 0.35, 1))',
        spring: 'var(--rare-easing-spring, cubic-bezier(0.34, 1.56, 0.64, 1))',
      },
      /* ── Keyframes ─────────────────────────────────────────── */
      keyframes: {
        'rare-error-shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-3px)' },
          '40%': { transform: 'translateX(3px)' },
          '60%': { transform: 'translateX(-2px)' },
          '80%': { transform: 'translateX(2px)' },
        },
        'rare-dropdown-grow': {
          from: { opacity: '0', transform: 'scaleY(0.92) translateY(-4px)' },
          to: { opacity: '1', transform: 'scaleY(1) translateY(0)' },
        },
        'rare-shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'rare-badge-pulse': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.05)', opacity: '0.9' },
        },
        'rare-overshoot': {
          '0%': { opacity: '0', transform: 'scale(1.03)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      /* ── Animations ────────────────────────────────────────── */
      animation: {
        'error-shake': 'rare-error-shake 0.3s ease-out',
        'dropdown-grow': 'rare-dropdown-grow 280ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shimmer': 'rare-shimmer 2s ease-in-out infinite',
        'badge-pulse': 'rare-badge-pulse 2s ease-in-out infinite',
        'overshoot': 'rare-overshoot 400ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
